//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_pelicula
    {
        public int peli_id { get; set; }
        public string peli_titu { get; set; }
        public Nullable<System.DateTime> peli_estreno { get; set; }
        public string peli_genero { get; set; }
        public Nullable<decimal> peli_precio { get; set; }
    }
}
